title:              Suibin's Blog
email:              sun1998s@outlook.com
#description:        A Blog Theme by Start Bootstrap
author:             Suibin Sun
baseurl:            "/"
url:                "https://sun98.github.io"

# Social Profiles
#twitter_username:   SBootstrap
github_username:    sun98
#facebook_username:  StartBootstrap
#instagram_username:  
linkedin_username: suibin-sun

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-QSK8XHBHGS # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
