name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Bundler and dependencies
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll \
        jekyll/builder gem install bundler jekyll-theme-clean-blog

    - name: Bundle lock
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll \
        jekyll/builder bundle lock

    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll \
        jekyll/builder bundle exec jekyll build
